language: haxe
haxe: "3.4.7"
dist: trusty
sudo: false

install:
  - haxelib install all --always
  - haxelib install hxcpp --always
  - haxelib dev hxparse libs/hxparse
  - haxelib dev hxtemplo libs/hxtemplo
  - haxelib dev hxargs libs/hxargs
  - haxelib dev markdown libs/haxe-markdown
  - haxelib dev dox libs/dox
  - haxelib list

script:
  - haxe gen.hxml
  - neko Gen.n

deploy:
  provider: script
  script: haxe --run DeployGhPages
  on:
    branch: master
  skip_cleanup: true
