language: haxe
haxe: "development"
dist: trusty
sudo: false

install:
  - haxelib install all --always
  - haxelib dev hxparse libs/hxparse
  - haxelib dev hxtemplo libs/hxtemplo
  - haxelib dev hxargs libs/hxargs
  - haxelib dev markdown libs/haxe-markdown
  - haxelib dev dox libs/dox
  - haxelib list

script:
  - haxe gen.hxml &&
    neko Gen.n &&
    haxe --run DeployGhPages
